### ISSUE TITLE
Add the URL after links when printing them

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/alexwlchan.net#865]
I've seen this done on the Flickr Foundation blog with the CSS:

```css
@media print {
  a[href]:after {
    content: " (" attr(href) ")"
  }
}
```

I should add something similar to my print stylesheet, once I work out exactly which links it should apply to.
